
---
server:
  port: 8080
  address: 127.0.0.1 # in production environments use reverse proxy, e.g. apache or nginx
  error:
    whitelabel.enabled: false
spring:
   application.name: AvG-S2-Producer
   artemis:
     mode: native
     broker-url: tcp://127.0.0.1:61616
     user: artemis
     password: p
logging:
  file:
    name: /tmp/application.log
  logback.rollingpolicy:
    file-name-pattern: ${LOGFILE}.%d{yyyy-MM-dd}.%i.gz
    max-file-size: 50MB
    max-history: 7
  pattern:
    console: "%clr(%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5level) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n%wEx"
    file: "%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5level ${PID:- } --- [%thread] %-40.40logger{39} : %m%n%wEx"
  threshold:
    console: info
    file: info
---
# --------------------------------------------------------
# P r o f i l e   " j m s "
# --------------------------------------------------------
jms:
  SendPricesTest: "SendPricesTest"
  stocks:
    updates: "stocks.updates"
    newOrder:
      Stuttgart: "stocks.newOrder.Stuttgart"
      Frankfurt: "stocks.newOrder.Frankfurt"
    c1:
      orderStatus:
        Stuttgart: "stocks.c1.orderStatus.Stuttgart"
        Frankfurt: "stocks.c1.orderStatus.Frankfurt"
    c2:
      orderStatus:
        Stuttgart: "stocks.c2.orderStatus.Stuttgart"
        Frankfurt: "stocks.c2.orderStatus.Frankfurt"
---
# --------------------------------------------------------
# P r o f i l e   " d e v "
# --------------------------------------------------------
spring:
  config.activate.on-profile: dev
logging:
  file.name: /tmp/application.log
  logback.rollingpolicy:
    file-name-pattern: ${logging.file.name}.%d{yyyy-MM-dd}.%i.gz
    max-file-size: 100KB
    max-history: 3
  pattern:
    console: "%clr(%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5level) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n%wEx"
    file: "%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5level ${PID:- } --- [%thread] %-40.40logger{39} : %m%n%wEx"
  threshold:
    console: trace
    file: trace
  level:
    de.hka_iwi_1.avg_s2_producer: trace
