#
# Copyright (c) 2024 - present Florian Sauer
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the ?Software?), to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions
# of the Software.
#
# THE SOFTWARE IS PROVIDED ?AS IS?, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
# LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Aufruf:   docker compose up
#           docker compose down
#
# Documentation: https://activemq.apache.org/components/artemis/documentation/latest/docker.html

services:
  artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: artemis_avg_s2_producer
    ports:
      - published: 61616
        target: 61616
      - published: 8161
        target: 8161
    volumes:
      - type: bind
        source: ../../../docker_tmp/artemis-instance
        target: /var/lib/artemis-instance
    env_file: artemis.env
    deploy:
      # https://docs.docker.com/compose/compose-file/deploy/#resources
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
        reservations:
          cpus: "2.0"
          memory: 2G
