#
# Aufruf:   docker compose up
#           docker compose down
#
# Documentation: https://activemq.apache.org/components/artemis/documentation/latest/docker.html

services:
  artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: artemis_avg_s2_producer
    ports:
      - published: 61616
        target: 61616
      - published: 8161
        target: 8161
    volumes:
      - type: bind
        source: ../../../docker_tmp/artemis-instance
        target: /var/lib/artemis-instance
    env_file: artemis.env
    deploy:
      # https://docs.docker.com/compose/compose-file/deploy/#resources
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
        reservations:
          cpus: "2.0"
          memory: 2G
